baseURL = 'https://fhl202.github.io/'
languageCode = 'en-us'
title = 'Hugo Lambert'
theme = "hyde"
publishDir = "docs"
#sectionPagesMenu = 'main'   # This is auto menus.

[params]
 themeColor = "theme-base-0b"
 description = "Atmospheric Scientist, University of Exeter"

[menus]
  [[menus.main]] 
     name = 'Research' 
     url = '/research/'   

[[menus.main]] 
     name = 'Group'
     url = '/group/'   
 
[[menus.main]] 
     name = 'Publications'
     url = '/pubs/'   


[[menus.main]] 
     name = 'Teaching and Admin'
     url = '/teaching/'
